### ISSUE TITLE
age transform breaks if value passed is not a string

### ISSUE THREAD

**Issue by surchs** [neurobagel/bagel-cli#71]
There are a couple of age related issues that need fixing:

- [ ] #85
- [x] #86
- [x] #87

The `transform_age` function signature allows `str, int, float` but really can only handle `str` right now. This hasn't surfaced because we only test on string values. But a (partially ?) numeric tsv column gets read by pandas as non-string type (object if mixed) by default, so we have to handle the case where we actually are passing numbers.

Edit: still a quick dump. There are two issues
- [x] Not all heuristics can handle all types. Eg the iso8601 heuristic breaks when (incorrectly) a number is passed, eg when the wrong heuristic is set in the data dictionary.
  - can always first cast to str
- [x] We don't have heuristics implemented for age values that are already the right format. Eg if I provide a float, there should be a heuristic that handles this. "Float" and "int" exist in the annotation tool, we should just add them
- [x] More generally: if we say a function can handle different types then we should test that
- [x] If a user picks the wrong heuristic in the data dictionary I don't think and things break, the error displayed is pretty confusing. So at least we could catch that and say something more intelligible
